Style/FileName:
  Exclude:
    - 'data/**/*'

Style/Next:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 60

Metrics/LineLength:
  Max: 99